# -*- mode: ruby -*-
# # vi: set ft=ruby :

# Specify minimum Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

require 'json'

# Read YAML file with box details
config = YAML.load_file('Vagrantfile.json')

# Create boxes
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # One VM per config file

  config.vm.box = config[:box]
  config.vm.hostname = config[:name]
  config.vm.network "private_network", ip: config[:ip]
  config.vm.provider "virtualbox" do |vb|
    vb.memory = config[:memory]
    vb.cpus = config[:cpu]
  end

    # srv.vm.synced_folder "./", "/home/vagrant/#{servers['name']}"

    # servers["shell_commands"].each do |sh|
    #   srv.vm.provision "shell", inline: sh["shell"]
    # end

    # srv.vm.provision :puppet do |puppet|
    #     puppet.temp_dir = "/tmp"
    #     puppet.options = ['--modulepath=/tmp/modules', '--verbose']
    #     puppet.hiera_config_path = "hiera.yaml"
    #
    #     end
    #   end
    # end
  end
