#!/bin/sh
#
# Fake Vagrant for acceptance testing
STATUS=".status"
if [ ! -f Vagrantfile ] ; then
  echo "No Vagrantfile!"
  exit 1
fi
case "$1" in
  status)
    echo "Current machine states:"
    echo
    if [ -f $STATUS ] ; then
      echo -e "default\t\t\trunning (virtualbox)"
    else
      echo -e "default\t\t\tsaved (virtualbox)"
    fi
    echo
    echo "To resume this VM, simply run `vagrant up`."
    ;;
  up)
    if [ -f $STATUS ] ; then
      echo "VM already running"
      exit 1
    else
      touch $STATUS
      echo "started VM"
    fi
    ;;
  suspend|destroy)
    if [ -f $STATUS ] ; then
      echo "shutting down VM"
      rm $STATUS
    else
      echo "VM not running so can't be stopped"
      exit 1
    fi
    ;;
  *)
    echo "invalid command"
    exit 1
    ;;
esac
